```cmd
(venv) $> git clone https://github.com/darksideoftheshmoo/pycell.git

(venv) $> git remote -v
origin  https://github.com/juniors90/pycell.git (fetch)
origin  https://github.com/juniors90/pycell.git (push)

(venv) $> git remote -h

(venv) $> git remote -h
```
Para *renombrar* el remoto `git remote rename <old> <new>`
```
(venv) $> git remote rename origin fork

(venv) $> git remote -v
fork    https://github.com/juniors90/pycell.git (fetch)
fork    https://github.com/juniors90/pycell.git (push)

(venv) $> git remote add origin https://github.com/darksideoftheshmoo/pycell

(venv) $> git remote -v
fork    https://github.com/juniors90/pycell.git (fetch)
fork    https://github.com/juniors90/pycell.git (push)
origin  https://github.com/darksideoftheshmoo/pycell.git (fetch)
origin  https://github.com/darksideoftheshmoo/pycell.git (push)

(venv) $> git checkout -b <name_new_branch>
Switched to a new branch 'name_new_branch'

(venv) $> git add -A

(venv) $> git commit -m "a message"

(venv) $> git push fork <name_new_branch>
```

# Example for load_data module

## Tablas sin procesar individuales

### Tabla out_all

Lo que buscamos es prober si los c√≥digos sirven

```python
df_tabla = create_df('../muestras_cellid/Position01/out_all')

#Le agrego el ucid
df_ucid = create_ucid_column(df_tabla, 1)

#Tabla mapping
df_mapping = create_df('../muestras_cellid/Position01/out_bf_fl_mapping')

#Obtengo un canal desde df_mapping
ch = get_chanel(df_mapping, 1)
```

In [1]:
from load_data import *

In [2]:
df_tabla = create_df('../muestras_cellid/Position01/out_all')

In [3]:
df_tabla

,cellID,t_frame,time,xpos,ypos,f_tot,a_tot,num_pix,fft_stat,perim,...,a_nucl6,f_local_bg,a_local_bg,a_local,f_local2_bg,a_local2_bg,a_local2,a_surf,con_vol _1,sphere_vol
0,0,0,0,29,725,231840.0,527.0,527,0.387982,100.79160,...,149.0,378.6183,131.0,143.0,372.9697,165.0,171.0,1521.736,7027.383,7078.397
1,0,0,0,29,725,127264.0,527.0,527,0.387982,100.79160,...,68.0,240.4300,100.0,143.0,241.2194,155.0,171.0,1521.736,7027.383,7078.397
2,0,0,0,29,725,6973770.0,527.0,527,0.387982,100.79160,...,118.0,12571.8300,138.0,143.0,12523.0500,171.0,171.0,1521.736,7027.383,7078.397
3,0,0,0,29,725,179631.0,527.0,527,0.387982,100.79160,...,149.0,312.5942,138.0,143.0,310.0760,171.0,171.0,1521.736,7027.383,7078.397
4,0,1,0,31,725,266441.0,614.0,614,0.443545,111.18920,...,148.0,383.6143,140.0,151.0,377.4458,166.0,172.0,1489.950,8429.729,8544.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24191,821,12,0,1007,124,240579.0,580.0,580,0.100221,93.25374,...,149.0,404.9592,98.0,132.0,407.8535,157.0,181.0,2043.168,9659.464,9351.288
24192,822,12,0,1025,145,84217.0,169.0,169,0.338916,53.85168,...,38.0,467.7846,65.0,96.0,469.5574,61.0,86.0,500.085,1315.201,1253.573
24193,822,12,0,1025,145,42199.0,169.0,169,0.338916,53.85168,...,62.0,249.1555,90.0,96.0,250.7000,80.0,86.0,500.085,1315.201,1253.573
24194,822,12,0,1025,145,2428966.0,169.0,169,0.338916,53.85168,...,81.0,11335.2900,82.0,96.0,10862.1700,76.0,86.0,500.085,1315.201,1253.573
24195,822,12,0,1025,145,74235.0,169.0,169,0.338916,53.85168,...,47.0,419.0641,78.0,96.0,421.0286,70.0,86.0,500.085,1315.201,1253.573

In [4]:
#Le agrego el ucid
df_ucid = create_ucid_column(df_tabla, 1)

In [5]:
df_ucid

,cellID,t_frame,time,xpos,ypos,f_tot,a_tot,num_pix,fft_stat,perim,...,f_local_bg,a_local_bg,a_local,f_local2_bg,a_local2_bg,a_local2,a_surf,con_vol _1,sphere_vol,ucid
0,0,0,0,29,725,231840.0,527.0,527,0.387982,100.79160,...,378.6183,131.0,143.0,372.9697,165.0,171.0,1521.736,7027.383,7078.397,100000000000
1,0,0,0,29,725,127264.0,527.0,527,0.387982,100.79160,...,240.4300,100.0,143.0,241.2194,155.0,171.0,1521.736,7027.383,7078.397,100000000000
2,0,0,0,29,725,6973770.0,527.0,527,0.387982,100.79160,...,12571.8300,138.0,143.0,12523.0500,171.0,171.0,1521.736,7027.383,7078.397,100000000000
3,0,0,0,29,725,179631.0,527.0,527,0.387982,100.79160,...,312.5942,138.0,143.0,310.0760,171.0,171.0,1521.736,7027.383,7078.397,100000000000
4,0,1,0,31,725,266441.0,614.0,614,0.443545,111.18920,...,383.6143,140.0,151.0,377.4458,166.0,172.0,1489.950,8429.729,8544.840,100000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24191,821,12,0,1007,124,240579.0,580.0,580,0.100221,93.25374,...,404.9592,98.0,132.0,407.8535,157.0,181.0,2043.168,9659.464,9351.288,100000000821
24192,822,12,0,1025,145,84217.0,169.0,169,0.338916,53.85168,...,467.7846,65.0,96.0,469.5574,61.0,86.0,500.085,1315.201,1253.573,100000000822
24193,822,12,0,1025,145,42199.0,169.0,169,0.338916,53.85168,...,249.1555,90.0,96.0,250.7000,80.0,86.0,500.085,1315.201,1253.573,100000000822
24194,822,12,0,1025,145,2428966.0,169.0,169,0.338916,53.85168,...,11335.2900,82.0,96.0,10862.1700,76.0,86.0,500.085,1315.201,1253.573,100000000822
24195,822,12,0,1025,145,74235.0,169.0,169,0.338916,53.85168,...,419.0641,78.0,96.0,421.0286,70.0,86.0,500.085,1315.201,1253.573,100000000822

Tabla mapping

In [6]:
df_mapping = create_df('../muestras_cellid/Position01/out_bf_fl_mapping')

In [7]:
df_mapping

,fluor,flag,t_frame,bright,bf_as_fl
0,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,0,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
1,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,0,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
2,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,0,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
3,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,0,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
4,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,1,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
5,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,1,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
6,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,1,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
7,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,1,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
8,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,2,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
9,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,2,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
10,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,2,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
11,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,2,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
12,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,3,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
13,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,3,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
14,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,3,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
15,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,3,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
16,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,4,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
17,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,4,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
18,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,4,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
19,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,4,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
20,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,5,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
21,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,5,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
22,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,5,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
23,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,5,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
24,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,6,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
25,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,6,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
26,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,6,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
27,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,6,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
28,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,7,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
29,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,7,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
30,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,7,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
31,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,7,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
32,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,8,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
33,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,8,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
34,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,8,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
35,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,8,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
36,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,9,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
37,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,9,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
38,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,9,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
39,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,9,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
40,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,10,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
41,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,10,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
42,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,10,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
43,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,10,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
44,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,11,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
45,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,11,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
46,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,11,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
47,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,11,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
48,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0,12,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
49,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,1,12,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
50,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,2,12,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0
51,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,3,12,D:\Mio\Trabajo\CONICET\IFIBYNE\Grupos_de_Inves...,0

Obtengo un canal desde `df_mapping`

In [8]:
channel = get_channel(df_mapping, 1)

In [9]:
channel

'rfp'

In [10]:
df = make_df('../muestras_cellid/Position01/out_all')

leyendo position:  1

In [11]:
df

,cellID,t_frame,time,xpos,ypos,f_tot,a_tot,num_pix,fft_stat,perim,...,a_local_bg,a_local,f_local2_bg,a_local2_bg,a_local2,a_surf,con_vol _1,sphere_vol,ucid,pos
0,0,0,0,29,725,231840.0,527.0,527,0.387982,100.79160,...,131.0,143.0,372.9697,165.0,171.0,1521.736,7027.383,7078.397,100000000000,1
1,0,0,0,29,725,127264.0,527.0,527,0.387982,100.79160,...,100.0,143.0,241.2194,155.0,171.0,1521.736,7027.383,7078.397,100000000000,1
2,0,0,0,29,725,6973770.0,527.0,527,0.387982,100.79160,...,138.0,143.0,12523.0500,171.0,171.0,1521.736,7027.383,7078.397,100000000000,1
3,0,0,0,29,725,179631.0,527.0,527,0.387982,100.79160,...,138.0,143.0,310.0760,171.0,171.0,1521.736,7027.383,7078.397,100000000000,1
4,0,1,0,31,725,266441.0,614.0,614,0.443545,111.18920,...,140.0,151.0,377.4458,166.0,172.0,1489.950,8429.729,8544.840,100000000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24191,821,12,0,1007,124,240579.0,580.0,580,0.100221,93.25374,...,98.0,132.0,407.8535,157.0,181.0,2043.168,9659.464,9351.288,100000000821,1
24192,822,12,0,1025,145,84217.0,169.0,169,0.338916,53.85168,...,65.0,96.0,469.5574,61.0,86.0,500.085,1315.201,1253.573,100000000822,1
24193,822,12,0,1025,145,42199.0,169.0,169,0.338916,53.85168,...,90.0,96.0,250.7000,80.0,86.0,500.085,1315.201,1253.573,100000000822,1
24194,822,12,0,1025,145,2428966.0,169.0,169,0.338916,53.85168,...,82.0,96.0,10862.1700,76.0,86.0,500.085,1315.201,1253.573,100000000822,1
24195,822,12,0,1025,145,74235.0,169.0,169,0.338916,53.85168,...,78.0,96.0,421.0286,70.0,86.0,500.085,1315.201,1253.573,100000000822,1

In [12]:
get_col_chan(df, df_mapping)

Agragando columnas chanles...

,pos,t_frame,ucid,cellID,time,xpos,ypos,a_tot,num_pix,fft_stat,...,f_nucl_tag6_tfp,f_nucl_tag6_yfp,f_local_bg_cfp,f_local_bg_rfp,f_local_bg_tfp,f_local_bg_yfp,f_local2_bg_cfp,f_local2_bg_rfp,f_local2_bg_tfp,f_local2_bg_yfp
0,1,0,100000000000,0,0,29,725,527.0,527,0.387982,...,1675334.0,54200.0,378.6183,240.4300,12571.83,312.5942,372.9697,241.2194,12523.05,310.0760
1,1,1,100000000000,0,0,31,725,614.0,614,0.443545,...,1473843.0,54020.0,383.6143,240.4676,12212.17,319.5286,377.4458,240.1235,12138.30,317.3976
2,1,2,100000000000,0,0,31,724,639.0,639,0.500724,...,1451150.0,46463.0,379.6064,241.2868,11988.62,322.5431,376.9560,242.0784,11993.09,323.3418
3,1,3,100000000000,0,0,31,725,688.0,688,0.591332,...,1566434.0,47871.0,390.2697,436.6727,11646.41,330.3378,391.3493,437.9252,11549.44,331.3429
4,1,4,100000000000,0,0,24,721,457.0,457,0.085026,...,1204067.0,52761.0,372.6058,241.3909,11593.46,330.6237,367.9105,242.5352,11503.96,329.0977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6044,1,12,100000000818,818,0,877,892,118.0,118,0.134565,...,1508359.0,21534.0,488.8594,251.3016,10583.71,390.7949,487.6154,250.7538,10554.46,391.1707
6045,1,12,100000000819,819,0,912,141,105.0,105,0.227042,...,1133418.0,72258.0,474.6167,248.2239,10156.90,599.3333,480.8393,250.9344,9729.20,634.9500
6046,1,12,100000000820,820,0,990,836,105.0,105,0.147196,...,829063.0,16551.0,467.2128,248.4762,10297.18,373.1200,466.5625,248.5968,10281.98,371.9800
6047,1,12,100000000821,821,0,1007,124,580.0,580,0.100221,...,986704.0,63176.0,459.3297,248.5424,11783.09,404.9592,449.5944,248.6808,11872.48,407.8535
6048,1,12,100000000822,822,0,1025,145,169.0,169,0.338916,...,1163581.0,21441.0,467.7846,249.1555,11335.29,419.0641,469.5574,250.7000,10862.17,421.0286

## Experimento largo

In [13]:
data_frame = read_cellidtable('../muestras_cellid')

.\Position01\out_all
leyendo position:  1
Agragando columnas chanles...
.\Position02\out_all
leyendo position:  2
Agragando columnas chanles...
.\Position03\out_all
leyendo position:  3
Agragando columnas chanles...

In [14]:
data_frame.head(10)

,pos,t_frame,ucid,cellID,time,xpos,ypos,a_tot,num_pix,fft_stat,...,f_nucl_tag6_tfp,f_nucl_tag6_yfp,f_local_bg_cfp,f_local_bg_rfp,f_local_bg_tfp,f_local_bg_yfp,f_local2_bg_cfp,f_local2_bg_rfp,f_local2_bg_tfp,f_local2_bg_yfp
0,1,0,100000000000,0,0,29,725,527.0,527,0.387982,...,1675334.0,54200.0,378.6183,240.4300,12571.83,312.5942,372.9697,241.2194,12523.05,310.0760
1,1,1,100000000000,0,0,31,725,614.0,614,0.443545,...,1473843.0,54020.0,383.6143,240.4676,12212.17,319.5286,377.4458,240.1235,12138.30,317.3976
2,1,2,100000000000,0,0,31,724,639.0,639,0.500724,...,1451150.0,46463.0,379.6064,241.2868,11988.62,322.5431,376.9560,242.0784,11993.09,323.3418
3,1,3,100000000000,0,0,31,725,688.0,688,0.591332,...,1566434.0,47871.0,390.2697,436.6727,11646.41,330.3378,391.3493,437.9252,11549.44,331.3429
4,1,4,100000000000,0,0,24,721,457.0,457,0.085026,...,1204067.0,52761.0,372.6058,241.3909,11593.46,330.6237,367.9105,242.5352,11503.96,329.0977
5,1,5,100000000000,0,0,22,720,440.0,440,0.131044,...,1089332.0,54297.0,371.3077,241.7769,10938.57,335.5439,367.4882,240.2014,11314.75,334.6094
6,1,6,100000000000,0,0,23,722,442.0,442,0.287140,...,905329.0,32556.0,370.1613,241.8516,10652.72,342.3250,371.7951,241.2385,10898.41,338.8240
7,1,7,100000000000,0,0,22,722,505.0,505,0.240440,...,993359.0,30577.0,374.4245,242.5877,10518.76,342.7701,370.6761,241.3916,10816.48,341.9917
8,1,8,100000000000,0,0,22,721,519.0,519,0.296899,...,985439.0,33382.0,372.1852,242.7723,10255.79,346.9907,366.4264,242.2746,10425.87,345.6716
9,1,9,100000000000,0,0,21,721,563.0,563,0.299308,...,1212789.0,23183.0,374.3645,239.4118,10363.22,350.4595,369.3356,240.6556,10436.39,349.3582

In [15]:
save_df(df,)

guardando archivo...

'se guard√≥ el archivo df.csv en el diretorio pydata'